// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4678.Cybercavs2016Code.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4678.Cybercavs2016Code.Robot;

/**
 *
 */
public class backToOuterWorks extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public backToOuterWorks() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.robotDrive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    int backUpState;

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.robotDrive.resetGoToDistanceState();
    	backUpState = 0;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	switch(backUpState) {
    	case 0:
	    		
	    	if (Robot.robotDrive.getBackLightSensorValue() > 1250) {
	    		Robot.robotDrive.resetEncoders();
	    		Robot.robotDrive.setRightMotor(0);
	    		Robot.robotDrive.setLeftMotor(0);
	    		backUpState++;
	    	}
	    	else {
	    		Robot.robotDrive.goToDistance(-200, -200, 0.35, 5, 5, 0.3, 0.3);
	    	}
	    	break;
    	case 1:
    		Robot.robotDrive.DrivePath(-150, 0, -150, 0);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.robotDrive.setRightMotor(0);
		Robot.robotDrive.setLeftMotor(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
